name: CI Pipeline

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
      IMAGE_TAG: ${{ github.sha }}

    steps:
      # Checkout source code
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Build & Push Backend Image
      - name: Build & push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./mern/backend
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/mern-backend:latest
            ${{ env.DOCKER_USER }}/mern-backend:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_USER }}/mern-backend:v1

      # Build & Push Frontend Image
      - name: Build & push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./mern/frontend
          push: true
          tags: |
            ${{ env.DOCKER_USER }}/mern-frontend:latest
            ${{ env.DOCKER_USER }}/mern-frontend:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_USER }}/mern-frontend:v1
